<a href="https://colab.research.google.com/github/ashia-002/python-oop-pandas-numpy/blob/main/Numpy_Basic/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

### Numpy array takes less time that list

In [7]:
from time import process_time

**list time taken**

In [8]:
py_list = [i for i in range(20000)]

start_time=process_time()

py_list = [i+5 for i in py_list]

end_time=process_time()

print(end_time - start_time)

0.0016434800000000305


numpy array time taken

In [9]:
np_array = np.array([i for i in range(20000)])

start_time=process_time()

np_array += 5

end_time=process_time()

print(end_time - start_time)

0.00026049699999997067


### Numpy Arrays

In [10]:
list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [11]:
np_ary = np.array([[1, 2, 3, 4, 5], [3, 4, 5, 7, 9]])
print(np_ary)
type(np_ary)

[[1 2 3 4 5]
 [3 4 5 7 9]]


numpy.ndarray

In [12]:
# how namy rows and columns
np_ary.shape

(2, 5)

In [18]:
# change the datatype of the array
np_ary.astype(float)
print(np_ary)

[[1 2 3 4 5]
 [3 4 5 7 9]]


In [13]:
# inspection of numpy array

In [14]:
# number of dimentions
print(np_ary.ndim)

2


In [16]:
print(len(np_ary))

2


In [15]:
# number of elements
print(np_ary.size)

10


In [17]:
print(np_ary.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Initial place holder in numpy

In [19]:
# a numpy aray using zeros
z = np.zeros((3,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
# a numpy array using ones
o = np.ones((4,3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# a array of any particular value using full()
p = np.full((4,5), 6)
print(p)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [22]:
# create a identity matrix
i = np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
# a numpy array with random values
r = np.random.random((3,4)) # will create values between 0 and 1
print(r)

[[0.66900562 0.77961125 0.48674713 0.68063844]
 [0.69538113 0.02771013 0.15753911 0.80518231]
 [0.70985161 0.2045242  0.02369701 0.59204327]]


In [24]:
# random values between specified range
r1 = np.random.randint(30, 60, (3,4)) #filling with values between 30 and 60
print(r1)

[[44 39 43 40]
 [39 32 49 40]
 [48 55 54 32]]


In [25]:
# filling with evenly spaced values
e = np.linspace(20, 50, 6)
print(e) # array type is float

[20. 26. 32. 38. 44. 50.]


In [26]:
# filling with evenly spaced values ---> specify the difference
s = np.arange(20, 60, 5)
print(s)

[20 25 30 35 40 45 50 55]


### Converting txt into numpy array

In [27]:
data = [
    [0.2536, 0.1008, 0.3857],
    [0.4839, 0.4536, 0.3561],
    [0.1292, 0.6875, 0.5929],
    [0.1781, 0.3049, 0.8928],
    [0.6253, 0.3486, 0.8791]
]


In [28]:
# first creating data.txt with values
with open("data.txt", "w") as f:
  f.write("value1 value2 value3\n")
  for r in data:
    formatted_row = " ".join(str(val) for val in r)
    f.write(f"{formatted_row}\n")


In [29]:
with open("data.txt", "r") as f:
  print(f.read())

value1 value2 value3
0.2536 0.1008 0.3857
0.4839 0.4536 0.3561
0.1292 0.6875 0.5929
0.1781 0.3049 0.8928
0.6253 0.3486 0.8791



loading the data.txt into numpy array

In [30]:
data = np.loadtxt('data.txt', skiprows=1)
print(data)
data.shape

[[0.2536 0.1008 0.3857]
 [0.4839 0.4536 0.3561]
 [0.1292 0.6875 0.5929]
 [0.1781 0.3049 0.8928]
 [0.6253 0.3486 0.8791]]


(5, 3)

Array Slicing

In [35]:
# taking only three row and two columns
s_data = data[:3, :2]
print(s_data)
s_data.shape

[[0.2536 0.1008]
 [0.4839 0.4536]
 [0.1292 0.6875]]


(3, 2)

In [36]:
m_data = data[ : , :2]
print(m_data)
m_data.shape

[[0.2536 0.1008]
 [0.4839 0.4536]
 [0.1292 0.6875]
 [0.1781 0.3049]
 [0.6253 0.3486]]


(5, 2)

### Array Mathematics

In [40]:
add = np.add(s_data , m_data[:3, :]) # both array shape (3,2)
print(add)

[[0.5072 0.2016]
 [0.9678 0.9072]
 [0.2584 1.375 ]]


In [41]:
m_data = m_data[:3, :]
sub = np.subtract(s_data, m_data)
print(sub)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# same way can use multipy and divide

In [43]:
#array-wise sum — the total of all values in the array.
data.sum()

np.float64(6.6721)

In [44]:
# minimum value of the entire array
data.min()

np.float64(0.1008)

In [47]:
# each column wise maximum
r1.max(axis=0)

array([48, 55, 54, 40])

In [49]:
# mean of the array
r1.mean()

np.float64(42.916666666666664)

In [56]:
# median
np.median(r1) # whole array
# np.median(r1, axis=0) #per column

# np.median(r1, axis=1) #per row

np.float64(41.5)