<a href="https://colab.research.google.com/github/ashia-002/python-oop-pandas-numpy/blob/main/Numpy_Basic/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Numpy array takes less time that list

In [2]:
from time import process_time

**list time taken**

In [3]:
py_list = [i for i in range(20000)]

start_time=process_time()

py_list = [i+5 for i in py_list]

end_time=process_time()

print(end_time - start_time)

0.0013230030000004334


numpy array time taken

In [4]:
np_array = np.array([i for i in range(20000)])

start_time=process_time()

np_array += 5

end_time=process_time()

print(end_time - start_time)

0.0002231830000001267


### Numpy Arrays

In [5]:
list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [9]:
np_ary = np.array([[1, 2, 3, 4, 5], [3, 4, 5, 7, 9]])
print(np_ary)
type(np_ary)

[[1 2 3 4 5]
 [3 4 5 7 9]]


numpy.ndarray

In [11]:
# how namy rows and columns
np_ary.shape

(2, 5)

In [ ]:
# inspection of numpy array

In [12]:
# number of dimentions
print(np_ary.ndim)

2


In [13]:
# number of elements
print(np_ary.size)

10


In [14]:
print(np_ary.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Initial place holder in numpy

In [17]:
# a numpy aray using zeros
z = np.zeros((3,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
# a numpy array using ones
o = np.ones((4,3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# a array of any particular value using full()
p = np.full((4,5), 6)
print(p)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [22]:
# create a identity matrix
i = np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
# a numpy array with random values
r = np.random.random((3,4)) # will create values between 0 and 1
print(r)

[[0.42959591 0.76693489 0.35112754 0.48004213]
 [0.86324535 0.54361883 0.14223166 0.52450522]
 [0.39790421 0.16840416 0.77877388 0.45945597]]


In [26]:
# random values between specified range
r1 = np.random.randint(30, 60, (3,4)) #filling with values between 30 and 60
print(r1)

[[39 54 55 42]
 [56 42 38 57]
 [47 34 59 45]]


In [31]:
# filling with evenly spaced values
e = np.linspace(20, 50, 6)
print(e) # array type is float

[20. 26. 32. 38. 44. 50.]


In [33]:
# filling with evenly spaced values ---> specify the difference
s = np.arange(20, 60, 5)
print(s)

[20 25 30 35 40 45 50 55]
